export const RECORDS_REQUEST = "RECORDS_REQUEST";
export const RECORDS_SUCCESS = "RECORDS_SUCCESS";
export const RECORDS_FAIL = "RECORDS_FAIL";
export const RECORDS_RESET = "RECORDS_RESET";

export const QUEUE_INDEX_CHANGE = "QUEUE_INDEX_CHANGE";
